// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0yGrlTeTwStTyuU68hQjuPAXEr9iOsfI',
    appId: '1:528047367291:web:9a97cb7eb0b20c346f2ede',
    messagingSenderId: '528047367291',
    projectId: 'transaction-app-a4db7',
    authDomain: 'transaction-app-a4db7.firebaseapp.com',
    storageBucket: 'transaction-app-a4db7.appspot.com',
    measurementId: 'G-K2KGV7HC8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRj9SkzUo44D-CnHyLJ168nSlMWKlnkM8',
    appId: '1:528047367291:android:128d28a5b9c615b06f2ede',
    messagingSenderId: '528047367291',
    projectId: 'transaction-app-a4db7',
    storageBucket: 'transaction-app-a4db7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD1CCdgcq42SjyQqpQPbFm0NgQKBxWeV4',
    appId: '1:528047367291:ios:ef751a2a74bf79746f2ede',
    messagingSenderId: '528047367291',
    projectId: 'transaction-app-a4db7',
    storageBucket: 'transaction-app-a4db7.appspot.com',
    iosBundleId: 'com.example.transactionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD1CCdgcq42SjyQqpQPbFm0NgQKBxWeV4',
    appId: '1:528047367291:ios:352296f5d5d8ea3c6f2ede',
    messagingSenderId: '528047367291',
    projectId: 'transaction-app-a4db7',
    storageBucket: 'transaction-app-a4db7.appspot.com',
    iosBundleId: 'com.example.transactionApp.RunnerTests',
  );
}
